import React from "react";

const RawData = [
  {
    ixBrch: 7440,
    ixJCd: 337,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10912,
    ProdCd: "",
    sProd: "Chicken Curry",
    ixProdCat: 70,
    ixProdCatSub: 195,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Chicken - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 100,
    endCost: 20000,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 100,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10687,
    ProdCd: "",
    sProd: " Pork Sisig 200g (5 servings/pack)",
    ixProdCat: 70,
    ixProdCatSub: 198,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Pork - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 100,
    endCost: 10000,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 100,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10686,
    ProdCd: "",
    sProd: " Sate Babi (5 sticks/pack)",
    ixProdCat: 70,
    ixProdCatSub: 198,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Pork - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 50,
    endCost: 3500,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 50,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10685,
    ProdCd: "",
    sProd: " Pork Barbecue (10 sticks/pack)",
    ixProdCat: 70,
    ixProdCatSub: 198,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Pork - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 50,
    endCost: 3500,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 50,
  },
  {
    ixBrch: 7438,
    ixJCd: 314,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10687,
    ProdCd: "",
    sProd: " Pork Sisig 200g (5 servings/pack)",
    ixProdCat: 70,
    ixProdCatSub: 198,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Pork - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 100,
    endCost: 10000,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 100,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10690,
    ProdCd: "",
    sProd: " Batchoy Kaldo Broth",
    ixProdCat: 70,
    ixProdCatSub: 200,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Soup - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 201,
    endCost: 0,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 201,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10689,
    ProdCd: "",
    sProd: " Batchoy",
    ixProdCat: 70,
    ixProdCatSub: 200,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Soup - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 500,
    endCost: 0,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 500,
  },
  {
    ixBrch: 7440,
    ixJCd: 337,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10696,
    ProdCd: "",
    sProd: " Adobong Kangkong",
    ixProdCat: 70,
    ixProdCatSub: 201,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Vegetables - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 1,
    endCost: 0,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 1,
  },
  {
    ixBrch: 7440,
    ixJCd: 311,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10696,
    ProdCd: "",
    sProd: " Adobong Kangkong",
    ixProdCat: 70,
    ixProdCatSub: 201,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Vegetables - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 50,
    endCost: 3500,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 50,
  },
  {
    ixBrch: 7440,
    ixJCd: 337,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10697,
    ProdCd: "",
    sProd: " Apan Apan (5 servings/pack)",
    ixProdCat: 70,
    ixProdCatSub: 201,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Vegetables - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 150,
    endCost: 7617,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 150,
  },
  {
    ixBrch: 7440,
    ixJCd: 360,
    libQtyCS: 0,
    libQtySC: 0,
    ixProd: 10696,
    ProdCd: "",
    sProd: " Adobong Kangkong",
    ixProdCat: 70,
    ixProdCatSub: 201,
    ixProdSubLink1: 0,
    ixProdSubLink2: 0,
    ixProdSubLink3: 0,
    ixProdSubLink4: 0,
    ixProdSubLink5: 0,
    sProdCat: "Finished Goods",
    sProdCatSub: "Vegetables - FG",
    sProdSubLink1: null,
    sProdSubLink2: null,
    sProdSubLink3: null,
    sProdSubLink4: null,
    sProdSubLink5: null,
    unit: "Pc/s",
    qtyBAL: 1,
    endCost: 45.89,
    vat: 0,
    qtyBAL_CS: 0,
    qtyBAL_SC: 0,
    qtyBAL_PC: 1,
  },
];

console.log("data:", RawData);

const Table = () => {
  return <pre>{JSON.stringify(RawData, null, 2)}</pre>;
};

export default Table;
